/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
    Prices: () => import('#controllers/admin/prices_controller'),
    Stations: () => import('#controllers/admin/stations_controller'),
    Tolls: () => import('#controllers/admin/tolls_controller'),
  },
  Optimize: () => import('#controllers/optimize_controller'),
  Session: () => import('#controllers/session_controller'),
}
