/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class StationAliasSchema extends BaseModel {
  static $columns = ['alias', 'createdAt', 'id', 'networkId', 'stationId', 'updatedAt'] as const
  $columns = StationAliasSchema.$columns
  @column()
  declare alias: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare networkId: number
  @column()
  declare stationId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TollNetworkSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'pricingMode', 'slug', 'updatedAt'] as const
  $columns = TollNetworkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare pricingMode: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TollPriceSchema extends BaseModel {
  static $columns = ['createdAt', 'distanceMeters', 'entryStationId', 'exitStationId', 'id', 'networkId', 'priceCents', 'updatedAt', 'validFrom', 'validTo', 'vehicleClass'] as const
  $columns = TollPriceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare distanceMeters: number | null
  @column()
  declare entryStationId: number
  @column()
  declare exitStationId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare networkId: number
  @column()
  declare priceCents: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.date()
  declare validFrom: DateTime
  @column.date()
  declare validTo: DateTime | null
  @column()
  declare vehicleClass: number
}

export class TollStationSchema extends BaseModel {
  static $columns = ['createdAt', 'gateType', 'id', 'latitude', 'longitude', 'name', 'networkId', 'operatorCode', 'updatedAt'] as const
  $columns = TollStationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gateType: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: number | null
  @column()
  declare longitude: number | null
  @column()
  declare name: string
  @column()
  declare networkId: number | null
  @column()
  declare operatorCode: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TollSchema extends BaseModel {
  static $columns = ['concession', 'createdAt', 'cumulativeMeters', 'elevation', 'gateType', 'gateTypeLabel', 'id', 'lambertX', 'lambertY', 'laneCount', 'latitude', 'longitude', 'milestone', 'milestoneDepartment', 'name', 'offsetMeters', 'referenceDate', 'road', 'side', 'stationId', 'updatedAt'] as const
  $columns = TollSchema.$columns
  @column()
  declare concession: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare cumulativeMeters: number | null
  @column()
  declare elevation: number | null
  @column()
  declare gateType: string | null
  @column()
  declare gateTypeLabel: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lambertX: number
  @column()
  declare lambertY: number
  @column()
  declare laneCount: number | null
  @column()
  declare latitude: number
  @column()
  declare longitude: number
  @column()
  declare milestone: number | null
  @column()
  declare milestoneDepartment: number | null
  @column()
  declare name: string
  @column()
  declare offsetMeters: number | null
  @column.date()
  declare referenceDate: DateTime | null
  @column()
  declare road: string | null
  @column()
  declare side: string | null
  @column()
  declare stationId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
